import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";

type ProjectInsert = Database["public"]["Tables"]["projects"]["Insert"];
type ProjectStatus = Database["public"]["Enums"]["project_status"];
type ProjectRag = Database["public"]["Enums"]["project_rag"];
type DeliveryMethod = Database["public"]["Enums"]["delivery_method"];

/** Demo portfolio (adapted from legacy sample_data_17_projects.sql). */
const SAMPLE: Array<Omit<ProjectInsert, "org_id">> = [
  {
    project_code: "PRJ-001",
    name: "ERP Core Upgrade",
    program: "Business Strategic",
    sponsor: "CFO",
    priority: "Critical",
    status: "In Progress" as ProjectStatus,
    rag: "Amber" as ProjectRag,
    current_phase: "Build",
    delivery_method: "Waterfall" as DeliveryMethod,
    start_date: "2025-07-01",
    end_date: "2026-12-31",
    budget: 1_200_000,
    capex_approved: 1_200_000,
    capex_incurred: 740_000,
    opex_approved: 0,
    opex_incurred: 0,
    benefits_target: 2_400_000,
    benefits_realised: 610_000,
    description: "Core ERP upgrade for finance operations.",
  },
  {
    project_code: "PRJ-002",
    name: "Omnichannel Portal",
    program: "Business Strategic",
    sponsor: "CCO",
    priority: "High",
    status: "In Progress" as ProjectStatus,
    rag: "Green" as ProjectRag,
    current_phase: "Testing",
    delivery_method: "Agile" as DeliveryMethod,
    start_date: "2025-06-01",
    end_date: "2026-10-31",
    budget: 850_000,
    capex_approved: 850_000,
    capex_incurred: 620_000,
    benefits_target: 1_500_000,
    benefits_realised: 900_000,
    description: "Unified customer portal across channels.",
  },
  {
    project_code: "PRJ-003",
    name: "Data Lakehouse",
    program: "IT Strategic",
    sponsor: "CTO",
    priority: "High",
    status: "In Progress" as ProjectStatus,
    rag: "Red" as ProjectRag,
    current_phase: "Design",
    delivery_method: "Hybrid" as DeliveryMethod,
    start_date: "2025-08-01",
    end_date: "2027-03-31",
    budget: 1_500_000,
    capex_approved: 1_500_000,
    capex_incurred: 580_000,
    benefits_target: 3_000_000,
    benefits_realised: 120_000,
    description: "Enterprise analytics lakehouse foundation.",
  },
  {
    project_code: "PRJ-004",
    name: "Cyber Hardening",
    program: "IT Strategic",
    sponsor: "CISO",
    priority: "Critical",
    status: "In Progress" as ProjectStatus,
    rag: "Green" as ProjectRag,
    current_phase: "Deployment",
    delivery_method: "Waterfall" as DeliveryMethod,
    start_date: "2025-05-01",
    end_date: "2026-06-30",
    budget: 320_000,
    opex_approved: 320_000,
    opex_incurred: 280_000,
    description: "Security baseline hardening programme.",
  },
  {
    project_code: "PRJ-005",
    name: "Store Workforce App",
    program: "CAPEX",
    sponsor: "COO",
    priority: "Medium",
    status: "In Progress" as ProjectStatus,
    rag: "Amber" as ProjectRag,
    current_phase: "Build",
    delivery_method: "Agile" as DeliveryMethod,
    start_date: "2025-09-01",
    end_date: "2026-11-30",
    budget: 410_000,
    capex_approved: 410_000,
    capex_incurred: 120_000,
    benefits_target: 780_000,
    benefits_realised: 40_000,
    description: "Mobile app for store workforce productivity.",
  },
  {
    project_code: "PRJ-006",
    name: "Supplier Portal Refresh",
    program: "Unfunded",
    sponsor: "CPO",
    priority: "Low",
    status: "On Hold" as ProjectStatus,
    rag: "Amber" as ProjectRag,
    current_phase: "Discovery",
    delivery_method: "Waterfall" as DeliveryMethod,
    start_date: "2026-01-01",
    end_date: "2027-06-30",
    budget: 0,
    capex_incurred: 15_000,
    benefits_target: 520_000,
    description: "Supplier collaboration portal refresh.",
  },
  {
    project_code: "PRJ-007",
    name: "AI Invoice Matching",
    program: "Business Strategic",
    sponsor: "CFO",
    priority: "High",
    status: "In Progress" as ProjectStatus,
    rag: "Green" as ProjectRag,
    current_phase: "Build",
    delivery_method: "Agile" as DeliveryMethod,
    start_date: "2025-10-01",
    end_date: "2026-08-31",
    budget: 220_000,
    opex_approved: 220_000,
    opex_incurred: 90_000,
    benefits_target: 650_000,
    benefits_realised: 50_000,
    description: "AI-assisted AP invoice matching.",
  },
  {
    project_code: "PRJ-008",
    name: "Field Service Mobile",
    program: "Business Strategic",
    sponsor: "COO",
    priority: "High",
    status: "In Progress" as ProjectStatus,
    rag: "Amber" as ProjectRag,
    current_phase: "Build",
    delivery_method: "Agile" as DeliveryMethod,
    start_date: "2025-07-15",
    end_date: "2026-09-30",
    budget: 380_000,
    capex_approved: 380_000,
    capex_incurred: 210_000,
    benefits_target: 920_000,
    benefits_realised: 180_000,
    description: "Field technician mobile service pack.",
  },
  {
    project_code: "PRJ-009",
    name: "ESG Reporting Automation",
    program: "IT Strategic",
    sponsor: "CFO",
    priority: "Medium",
    status: "In Progress" as ProjectStatus,
    rag: "Green" as ProjectRag,
    current_phase: "Design",
    delivery_method: "Waterfall" as DeliveryMethod,
    start_date: "2025-11-01",
    end_date: "2026-07-31",
    budget: 150_000,
    opex_approved: 150_000,
    opex_incurred: 40_000,
    benefits_target: 300_000,
    description: "Automated ESG metrics and reporting.",
  },
  {
    project_code: "PRJ-010",
    name: "Identity Access Modernisation",
    program: "IT Strategic",
    sponsor: "CISO",
    priority: "Critical",
    status: "In Progress" as ProjectStatus,
    rag: "Amber" as ProjectRag,
    current_phase: "Testing",
    delivery_method: "Hybrid" as DeliveryMethod,
    start_date: "2025-04-01",
    end_date: "2026-12-31",
    budget: 690_000,
    capex_approved: 690_000,
    capex_incurred: 480_000,
    description: "SSO, MFA, and privileged access uplift.",
  },
  {
    project_code: "PRJ-011",
    name: "CRM 360 Consolidation",
    program: "Business Strategic",
    sponsor: "CCO",
    priority: "High",
    status: "In Progress" as ProjectStatus,
    rag: "Red" as ProjectRag,
    current_phase: "Design",
    delivery_method: "Waterfall" as DeliveryMethod,
    start_date: "2025-08-15",
    end_date: "2027-01-31",
    budget: 980_000,
    capex_approved: 980_000,
    capex_incurred: 310_000,
    benefits_target: 2_100_000,
    benefits_realised: 95_000,
    description: "Single customer 360 CRM consolidation.",
  },
  {
    project_code: "PRJ-012",
    name: "Cloud Cost Optimisation",
    program: "IT Strategic",
    sponsor: "CTO",
    priority: "Medium",
    status: "In Progress" as ProjectStatus,
    rag: "Green" as ProjectRag,
    current_phase: "Testing",
    delivery_method: "Agile" as DeliveryMethod,
    start_date: "2025-09-01",
    end_date: "2026-05-31",
    budget: 180_000,
    opex_approved: 180_000,
    opex_incurred: 110_000,
    benefits_target: 450_000,
    benefits_realised: 210_000,
    description: "FinOps tooling and reserved capacity programme.",
  },
  {
    project_code: "PRJ-013",
    name: "Warehouse WMS Upgrade",
    program: "CAPEX",
    sponsor: "COO",
    priority: "High",
    status: "In Progress" as ProjectStatus,
    rag: "Amber" as ProjectRag,
    current_phase: "Build",
    delivery_method: "Waterfall" as DeliveryMethod,
    start_date: "2025-06-01",
    end_date: "2026-12-15",
    budget: 1_100_000,
    capex_approved: 1_100_000,
    capex_incurred: 520_000,
    benefits_target: 1_800_000,
    benefits_realised: 220_000,
    description: "Warehouse management system upgrade.",
  },
  {
    project_code: "PRJ-014",
    name: "Contact Centre AI Assist",
    program: "Business Strategic",
    sponsor: "CCO",
    priority: "Medium",
    status: "In Progress" as ProjectStatus,
    rag: "Green" as ProjectRag,
    current_phase: "Discovery",
    delivery_method: "Agile" as DeliveryMethod,
    start_date: "2025-12-01",
    end_date: "2026-09-30",
    budget: 260_000,
    capex_approved: 260_000,
    capex_incurred: 45_000,
    benefits_target: 700_000,
    description: "Agent assist AI for contact centre.",
  },
  {
    project_code: "PRJ-015",
    name: "API Gateway Platform",
    program: "IT Strategic",
    sponsor: "CTO",
    priority: "Critical",
    status: "In Progress" as ProjectStatus,
    rag: "Amber" as ProjectRag,
    current_phase: "Build",
    delivery_method: "Hybrid" as DeliveryMethod,
    start_date: "2025-05-15",
    end_date: "2026-11-30",
    budget: 740_000,
    capex_approved: 740_000,
    capex_incurred: 390_000,
    benefits_target: 1_200_000,
    benefits_realised: 150_000,
    description: "Enterprise API gateway and developer portal.",
  },
  {
    project_code: "PRJ-016",
    name: "HR Self-Service Portal",
    program: "Business Strategic",
    sponsor: "CHRO",
    priority: "Medium",
    status: "In Progress" as ProjectStatus,
    rag: "Green" as ProjectRag,
    current_phase: "Build",
    delivery_method: "Agile" as DeliveryMethod,
    start_date: "2025-10-15",
    end_date: "2026-08-15",
    budget: 195_000,
    opex_approved: 195_000,
    opex_incurred: 70_000,
    benefits_target: 410_000,
    benefits_realised: 25_000,
    description: "Employee HR self-service experiences.",
  },
];

export function getSampleProjects(orgId: string): ProjectInsert[] {
  return SAMPLE.map((p) => ({ ...p, org_id: orgId }));
}

/** Insert demo projects into the signed-in user's organization. */
export async function seedSamplePortfolio(orgId: string): Promise<{ count: number }> {
  const { data: rpcCount, error: rpcError } = await supabase.rpc("seed_sample_portfolio");
  if (!rpcError && typeof rpcCount === "number") {
    return { count: rpcCount };
  }

  // Fallback if RPC not applied yet — requires org_admin insert policy
  const payload = getSampleProjects(orgId);
  const { error } = await supabase.from("projects").insert(payload);
  if (error) {
    const hint = rpcError?.message ? ` (RPC: ${rpcError.message})` : "";
    throw new Error(`${error.message}${hint}`);
  }
  return { count: payload.length };
}

/** Move orphaned sample projects into the caller's org (admin only). */
export async function claimOrphanProjects(): Promise<number> {
  const { data, error } = await supabase.rpc("claim_orphan_projects");
  if (error) throw error;
  return typeof data === "number" ? data : 0;
}
